[profile.default]
src            = "src"
out            = "out"
libs           = ["lib"]
test           = "test"
script         = "script"
solc           = "0.8.20"
optimizer      = true
optimizer_runs = 200

[profile.default.fuzz]
runs = 2000

[rpc_endpoints]
sepolia   = "${SEPOLIA_RPC_URL}"
localhost = "http://127.0.0.1:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
